apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Chart.Name }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Chart.Name }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -ecx
        - |
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
           exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:7350/
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: game-backend
        ports:
        - containerPort: 7349
        - containerPort: 7350
        - containerPort: 7351
        resources: {}
      restartPolicy: Always
      serviceAccountName: "default"
      volumes: null
status: {}
